---
output: html_document
---
###App-CancerSurv Documentation
**Author: Michael Shipman**  
**Date: August 19, 2014**  

*This is the background documentation for the Shiny R application titled 'App-CancerSurv'*. 

####About the Application
'App-CancerSurv' is a ShinyR application that basically provides the  statistics regarding probabilility of developing cancer in a body site, probability of dying of cancer in certain body sites, and then calculating the probability of survival given that an individual has developed cancer in a body site.  The statistics are shown in reference to the probability for females and males.  

The App does require the cancer statistics dataset held in 'ACSDiagData.xlsx' to reside in the ShinyApp.io virtual server working directory, so that the application can read the dataset into the working environment.

####Application Operation
*The CancerSurv-App operation is very straightforward.*  
  
1.The CancerSurv-App is launched in RStudio Console as using the command 'runApp("App-CancerSurv")'. If the ACSDiagData.xlsx file is not in the working directory, then the application will not run properly.  
  
2.The application will open with "All Sites" selected, referring to overall statistics and survival rate calculations.   
  
3.The user is directed in the left side panel of the user interface (UI) to select a body site from the drop down selections.  
  
4.Once a selection is made, the probability of development and probability of dying of cancer at the selected site is then automatically rendered to the user in the main panel of the UI.  
  
5.The App then displays a calculated probability of survival based on the development and death probabilies for the selected site in the main panel of the UI.  
  
6.The user can select as many sites as he or she wishes.  
  
####The Cancer Source Data for the Application
The statstics are based on cancer survival statistics acquired from the American Cancer Society's website at http://www.cancer.org/acs/groups/content/@research/documents/document/acspc-041777.pdf. The source document is 'The Lifetime Probability of Developing and Dying from Cancer 2008-2010' from the ACS Survellance, 2014.  The data was transferred to 'ACSDiagData.xlsx' file since the .pdf file was not conducive to being read by R as a data source document.
